### ISSUE TITLE
Fix errors detected by cppcheck

### ISSUE THREAD

**Issue by thomas-moulard** [stack-of-tasks/dynamic-graph#10]
Cppcheck can be used to easily detect errors in software.

Steps:

<pre>
# On Ubuntu, cppcheck can be installed through apt:
apt-get install cppcheck

# Run it.
cd dynamic-graph # go to the project source top-level
cppcheck --enable=all include tests src 2> err.txt
</pre>

Here are the results:

<pre>
[src/dgraph/interpreter.cpp:295]: (style) The scope of the variable name can be reduced
[src/dgraph/interpreter.cpp:503]: (possible style) Pre-Incrementing variable 'iter' is preferred to Post-Incrementing
[src/dgraph/plugin-loader.cpp:147]: (error) Dangerous iterator usage. After erase the iterator is invalid so dereferencing it or comparing it with another iterator is invalid.
[src/dgraph/pool.cpp:113]: (possible style) Pre-Incrementing variable 'entPtr' is preferred to Post-Incrementing
[src/dgraph/pool.cpp:177]: (possible style) Pre-Incrementing variable 'iter' is preferred to Post-Incrementing
[src/dgraph/pool.cpp:196]: (possible style) Pre-Incrementing variable 'iter' is preferred to Post-Incrementing
[src/dgraph/pool.cpp:224]: (possible style) Pre-Incrementing variable 'iter' is preferred to Post-Incrementing
[src/shell/functions.cpp:375]: (style) The scope of the variable opt can be reduced
[src/shell/functions.cpp:375]: (style) The scope of the variable filename can be reduced
[src/shell/functions.cpp:38]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:57]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:79]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:95]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:121]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:135]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:144]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:175]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:205]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:239]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:258]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:289]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:317]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:366]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:399]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:418]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:442]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/shell/functions.cpp:455]: (style) Function parameter 'cmdLine' is passed by value. It could be passed by reference instead.
[src/traces/tracer-real-time.cpp:55]: (style) Redundant condition. It is safe to deallocate a NULL pointer
[src/traces/tracer-real-time.cpp:64]: (style) Redundant condition. It is safe to deallocate a NULL pointer
[src/traces/tracer-real-time.cpp:109]: (style) Function parameter 'n' is passed by value. It could be passed by reference instead.
[src/traces/tracer.cpp:41]: (style) Function parameter 'n' is passed by value. It could be passed by reference instead.
[tests/custom-entity.cpp:37]: (style) Function parameter 'n' is passed by value. It could be passed by reference instead.
</pre>

**Comment by olivier-stasse** [comment]
cppcheck has been applied and is integrated in the travis scripts.
