### ISSUE TITLE
What is Contiifstream?

### ISSUE THREAD

**Issue by thomas-moulard** [stack-of-tasks/dynamic-graph#12]
This class should be documented, and does not seem to be used anywhere.

**Comment by olivier-stasse** [comment]
To me it looks like the new class RealTimeLogger is doing what should have done Contiifstream.
I propose to remove it.

**Comment by jmirabel** [comment]
I had a look at this class. I think it does the opposite. It reads a file and put it into a list of string. I do not know where it is used.
