### ISSUE TITLE
Handle unplugged signals

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/dynamic-graph#21]
Currently there is no way of handling unplugged signals in dynamic-graph. As a result, if there is any false access request made by any entity, it leads to a segfault. Then depending on the layers above the segfault, the error may be trackable in 1 hour or 3. We need a proper mechanism to address these null pointer accesses in unplugged signals

**Comment by olivier-stasse** [comment]
You have an exception thrown when a signal is unplugged:
https://github.com/stack-of-tasks/dynamic-graph/blob/master/include/dynamic-graph/signal-ptr.t.cpp#L41
We could catch this in the Python interpreter and then send some explanation ?
Would that be acceptable ?

**Comment by proyan** [comment]
Thanks @olivier-stasse for the comment. It seems my initial post was misinformed.
I faced this issue while debugging openhrp3-hrp2.  Unfortunately, now I realize, that the faulty signal access was handled here, and as a result the error I received was an exception in the CORBA server instead of a segfault. It took me some time to figure out the problem.
Perhaps a solution would be to make sure that before we call start_dynamic_graph, we can make sure all descendants of robot.device.control are plugged. This would be useful to pre-empt such problems.
