### ISSUE TITLE
writeGraph generates wrong graph

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/dynamic-graph#22]
When a task (T) in two solvers (A and B), the graph generated by `writeGraph` is not correct. The graph that is generated looks like:
```
subgraph "A" {
 T
}
subgraph "B" {
 T
}
```

T is shown only in one of the solver.

**Comment by proyan** [comment]
I'll have a look at it during the week. Do you need an immediate resolution of this issue?

**Comment by jmirabel** [comment]
No, there is no need for immediate resolution.

**Comment by proyan** [comment]
ok, thanks for raising the issue.

**Comment by jmirabel** [comment]
I believe this is not dynamic-graph faults (although a work-around could probably be implemented in sot-core).
