### ISSUE TITLE
[tests] Missing file debug-logger-winit in tests in devel branch

### ISSUE THREAD

**Issue by NoelieRamuzat** [stack-of-tasks/dynamic-graph#38]
I think you forgot to add the test file _debug-logger-winit_ in your last commit :
"[tests] Add tests on sendMsgs without initialization."
You only changed the CMakeList by adding DYNAMIC_GRAPH_TEST(debug-logger-winit) without adding the file, this leads to errors during compilation.

**Comment by olivier-stasse** [comment]
Fixed by 8af26000842694c330bdafaf3ae61c533b51d4ff
