### ISSUE TITLE
Unplugging a signal?

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/dynamic-graph#42]
How do I completely unplug a signal once it is plugged?

**Comment by olivier-stasse** [comment]
I will update the documentation accordingly. But I guess that the best is to give a python answer not a C++ one.

**Comment by gabrielebndn** [comment]
Yes, in Python. I remember finding a way, there was an `unplug` command if I am not wrong

**Comment by olivier-stasse** [comment]
Then if this fine with you I will do this on dynamic-graph-python on not on dynamic-graph. Thanks for answering quicker than I do...

**Comment by gabrielebndn** [comment]
dynamic-graph-python will be fine, I think :)
