### ISSUE TITLE
Access specifiers in macros

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/dynamic-graph#44]
Macros `DECLARE_SIGNAL_OUT`:
https://github.com/stack-of-tasks/dynamic-graph/blob/1bcf9a54b7c3ea75d9230a15f25df92af28cbcd5/include/dynamic-graph/signal-helper.h#L41-L45
and `DECLARE_SIGNAL_INNER`
https://github.com/stack-of-tasks/dynamic-graph/blob/1bcf9a54b7c3ea75d9230a15f25df92af28cbcd5/include/dynamic-graph/signal-helper.h#L62-L66

both contain access specifiers, which causes the access to be `protected` after one of these macros is employed, which is totally unexpected if, for instance, it used to be `public`.

Is there a reason why we *want* these functions to be protected? Can't we just leave remove the access specifiers and let the user just make sure everything is public?

**Comment by jmirabel** [comment]
The motivation I can see for this access specifiers is that the API of entities are signals.

**Comment by olivier-stasse** [comment]
I confirm that the answer of @jmirabel is correct.
